# Generated by Django 3.2.3 on 2021-08-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('search_medicine', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('picture', models.ImageField(upload_to='pics')),
                ('expirydate', models.DateField()),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'donationform',
            },
        ),
    ]
