# Generated by Django 3.2.3 on 2021-07-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('number_of_tablets', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
