# Generated by Django 3.2.3 on 2021-08-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationform',
            name='picture',
        ),
        migrations.AlterModelTable(
            name='donationform',
            table=None,
        ),
    ]
