# Generated by Django 3.2.3 on 2021-08-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210815_1804'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donationform',
            table='donationform',
        ),
    ]
